services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
      DATABASE_URL: postgres://postgres:password@postgres:5432/postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
